name: Generate Contributions

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day
  push:
    branches:
      - main

jobs:
  make_contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a new file
        run: echo "Automated contribution $(date)" > contribution-$(date +%Y-%m-%d).txt

      - name: Commit file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated contribution for $(date +%Y-%m-%d)"
          git push
